name: CI

on:
  schedule:
    - cron: '0 */12 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2      
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: build app with debug variant
        run: |
          cd ./android
          ./gradlew assembleDebug
      - name: distribute on firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: main
          file: ./android/app/build/outputs/apk/debug/app-debug.apk
