name: CI

on:
  push:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2      
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run detekt
        run: |
          cd ./android
          ./gradlew detekt --stacktrace
      - name: Save artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report
          path: android/app/build/reports/detekt/detekt.html

          
