name: CI

on:
  push:
    branches:
      - master

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2      
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run detekt
        run: |
          cd ./android
          ./gradlew detektAll --stacktrace
      - name: Save artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: detekt-report
          path: android/build/reports/detekt/detekt.html

  remove-unused-resources:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2      
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Run unused resources task
        run: |
          cd ./android
          ./gradlew removeUnusedResources
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'Remove unused resources'
          assignees: aka-godinez
          reviewers: aka-godinez
          commit-message: 'Remove unused resources'
          delete-branch: true

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2      
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Unit tests
        run: |
          cd ./android
          ./gradlew koverReport --stacktrace
      # - name: Upload test reports to Codecov
      #   uses: codecov/codecov-action@v2.1.0



