name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2      
      - name: setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: update version file
        run: |
          cd ./android
          CURRENT_VERSION=$(cat ./current-version.txt)
          NEXT_VERSION=$(($CURRENT_VERSION + 1))
          echo $NEXT_VERSION > current-version.txt
          git config --global user.name 'israel nascimento'
          git config --global user.email 'dev.israelnascimento@gmail.com'
          git add .
          git commit -m "chore: update version to $NEXT_VERSION"
          git tag -a "$NEXT_VERSION" -m "$NEXT_VERSION"
          git push origin "$NEXT_VERSION"
          git push origin master
      - name: build app with debug variant
        run: |
          cd ./android
          ./gradlew assembleDebug -PversionName="1.$(cat ./current-version.txt).0"
      - name: distribute on firebase distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: main
          file: ./android/app/build/outputs/apk/debug/app-debug.apk
